spring.application.name=book-store-be

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/db_book_store
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database=mysql


blackcode.app.jwtSecret=5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA
blackcode.app.jwtExpirationMs=3600000
blackcode.app.jwtRefreshExpirationMs=360000000


#logging.level.org.springframework=INFO
logging.level.org.springframework.security=DEBUG